GET http://localhost:3000/api/v1/movies

###

POST http://localhost:3000/api/v1/movies
Content-Type: application/json

{
    "title": "Hereditary",
    "genre": "horror",
    "status": "watched",
    "rating": 3,
    "notes": ""
}

###

PATCH http://localhost:3000/api/v1/movies/MOVIE_ID_HERE
Content-Type: application/json

{
    "status": "watched",
    "rating": 4
}

###

DELETE http://localhost:3000/api/v1/movies/MOVIE_ID_HERE


