GET https://watchlist-crudapi-9855cdafdb36.herokuapp.com/movies

###

POST https://watchlist-crudapi-9855cdafdb36.herokuapp.com/movies
Content-Type: application/json

{
    "title":"Hereditary",
    "genre":"horror", 
    "status":"watched",
    "rating": "5"
    
}

###

PATCH https://watchlist-crudapi-9855cdafdb36.herokuapp.com/movies/6a2c80f5aab3b11c965c56da

###

DELETE  https://watchlist-crudapi-9855cdafdb36.herokuapp.com/movies/6a2c80f5aab3b11c965c56da


